import type { InputStyle, InputType } from "$models";

type InputFull = InputType | 'digital' | 'analogic';


export const styles: Partial<Record<InputFull, string | InputStyle>> = {
    input       : 'block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-gray-400 focus:ring-0.5 focus:ring-gray-400 placeholder:text-gray-400 sm:text-sm disabled:bg-slate-100 disabled:text-zinc-500 dark:disabled:text-zinc-400 dark:bg-zinc-900 dark:text-zinc-300 dark:border-zinc-700 dark:disabled:bg-zinc-700',
	textarea    : 'w-full rounded-md border border-gray-300 shadow-sm focus:border-gray-400 focus:ring-0.5 focus:ring-gray-400 placeholder:text-gray-400 sm:text-sm disabled:border-gray-200 dark:disabled:text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300 dark:border-zinc-700 dark:disabled:bg-zinc-700 dark:disabled:placeholder:text-zinc-400',	
	button      : 'w-full inline-flex h-12 text-white items-center justify-center rounded-md bg-black px-[21px] text-[15px] font-semibold text-background shadow-minitransition-all duration-200 hover:bg-dark/95 active:scale-[0.98] active:bg-zinc-700 disabled:scale-100 disabled:bg-zinc-600 disabled:cursor-not-allowed disabled:opacity-50 dark:hover:bg-zinc-800 dark:text-zinc-200 dark:disabled:bg-zinc-700 dark:disabled:text-zinc-400',
    check       : {
		label		: 'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 dark:text-zinc-300',
		box			: 'read read-only:cursor-help peer inline-flex size-[25px] items-center justify-center rounded-md border border-zinc-400 dark:border-zinc-600 bg-foreground transition-all duration-150 ease-in-out active:scale-98 data-[state=unchecked]:border-border-input data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:border-dark-40',
	},
    select      : {
        box         : 'flex w-full items-center justify-between rounded-md border-[1.5px] border-zinc-300 bg-white px-3 py-2 text-sm transition-all focus-visible:outline-none focus-visible:border-[2px] focus-visible:border-zinc-400 dark:focus-visible:border-zinc-500 disabled:cursor-not-allowed disabled:opacity-50 dark:border-zinc-700 dark:bg-zinc-900',
        content     : 'absolute z-[9999] overflow-hidden rounded-md border border-zinc-200 bg-white text-zinc-950 shadow-xl dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-50',
        item        : 'flex w-full items-center justify-between px-3 py-2 text-sm transition-colors rounded-md focus-visible:outline-none focus-visible:bg-zinc-100 dark:focus-visible:bg-zinc-700 hover:bg-zinc-200/50 dark:hover:bg-zinc-700/50 data-[hovered=true]:bg-zinc-300/50 dark:data-[hovered=true]:bg-zinc-700 data-[selected=true]:bg-zinc-200/50 dark:data-[selected=true]:bg-zinc-700/50',
        group       : 'dark:text-zinc-400 flex w-full items-center justify-between px-3 py-2 text-sm font-bold bg-transparent dark:bg-transparent hover:bg-zinc-200 dark:hover:bg-zinc-700/50 focus:bg-zinc-100 rounded-md dark:focus:bg-zinc-700 focus:outline-none transition-colors',
        input       : 'block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-gray-400 focus:ring-0.5 focus:ring-gray-400 placeholder:text-gray-400 sm:text-sm disabled:bg-slate-100 disabled:text-zinc-500 dark:disabled:text-zinc-400 dark:bg-zinc-900 dark:text-zinc-300 dark:border-zinc-700 dark:disabled:bg-zinc-700',
    },
    datepicker  : {
        box			: 'rounded-md flex h-10 w-full select-none items-center border border-border-input dark:border-zinc-700 dark:text-zinc-300 bg-white dark:bg-zinc-900 px-2 py-3 text-sm tracking-[0.01em]-500 dark:data-[disabled]:bg-zinc-700 data-[disabled]:bg-zinc-100 focus-within:border-border-input-hover focus-within:shadow-date-field-focus hover:border-border-input-hover',
        content		: 'rounded-md border border-dark-10 shadow-md text-zinc-800 dark:text-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 p-3 shadow-popover dark:text-zinc-300',
		label		: 'block select-none text-sm font-medium dark:text-zinc-200 dark:data-[disabled]:text-zinc-400 data-[disabled]:text-zinc-500',
        item        : 'size-8 flex items-center justify-center rounded-md text-sm relative transition-colors duration-200 [&.current-month:not(.out-of-range):not(.invalid-date)]:hover:bg-zinc-200 [&.current-month:not(.out-of-range):not(.invalid-date)]:hover:text-foreground [&.current-month:not(.out-of-range):not(.invalid-date)]:dark:hover:bg-zinc-700 [&.current-month:not(.out-of-range):not(.invalid-date)]:dark:hover:text-white [&:not(.current-month)]:text-zinc-300 [&:not(.current-month)]:cursor-not-allowed [&:not(.current-month)]:opacity-50 [&.out-of-range]:text-zinc-300 [&.out-of-range]:dark:text-zinc-500 [&.out-of-range]:cursor-not-allowed [&.out-of-range]:opacity-60 [&.invalid-date]:text-zinc-300 [&.invalid-date]:dark:text-zinc-500 [&.invalid-date]:cursor-not-allowed [&.selected]:bg-blue-500 [&.selected]:text-white [&.selected]:font-bold [&.selected]:hover:bg-blue-600 [&.today:not(.selected):not(.invalid)]:font-bold [&.today:not(.selected):not(.invalid)]:text-primary',
        rangeItem   : 'size-8 flex items-center justify-center rounded-md text-sm relative transition-colors duration-200 [&:not(.current-month)]:text-zinc-300 [&:not(.current-month)]:cursor-not-allowed [&:not(.current-month)]:opacity-50 [&.out-of-range]:text-zinc-300 [&.out-of-range]:dark:text-zinc-500 [&.out-of-range]:cursor-not-allowed [&.out-of-range]:opacity-60 [&.invalid-date]:text-zinc-300 [&.invalid-date]:dark:text-zinc-500 [&.invalid-date]:cursor-not-allowed [&.current-month:not(.out-of-range):not(.invalid-date)]:hover:bg-blue-100 [&.current-month:not(.out-of-range):not(.invalid-date)]:dark:hover:bg-blue-900/30 [&.start-date]:bg-blue-500 [&.start-date]:text-white [&.start-date]:font-bold [&.start-date]:rounded-l-md [&.end-date]:bg-blue-500 [&.end-date]:text-white [&.end-date]:font-bold [&.end-date]:rounded-r-md [&.in-range:not(.start-date):not(.end-date)]:bg-blue-100 [&.in-range:not(.start-date):not(.end-date)]:dark:bg-blue-900/30 [&.in-range:not(.start-date):not(.end-date)]:text-foreground [&.in-range:not(.start-date):not(.end-date)]:hover:bg-blue-200 [&.in-range:not(.start-date):not(.end-date)]:dark:hover:bg-blue-800/30 [&.in-hover-range:not(.start-date):not(.end-date):not(.in-range)]:bg-blue-50 [&.in-hover-range:not(.start-date):not(.end-date):not(.in-range)]:dark:bg-blue-900/20 [&.in-hover-range:not(.start-date):not(.end-date):not(.in-range)]:text-foreground [&.today:not(.start-date):not(.end-date):not(.in-range):not(.in-hover-range)]:font-bold [&.today:not(.start-date):not(.end-date):not(.in-range):not(.in-hover-range)]:text-blue-500'
    },
    digital : {
        box		: 'rounded-md flex h-10 w-full select-none items-center border border-border-input dark:border-zinc-700 dark:text-zinc-300 bg-white dark:bg-zinc-900 px-2 py-3 text-sm tracking-[0.01em]-500 dark:data-[disabled]:bg-zinc-700 data-[disabled]:bg-zinc-100 focus-within:border-border-input-hover focus-within:shadow-date-field-focus hover:border-border-input-hover flex justify-between items-center px-3',
        content : 'absolute float-right right-0 z-40 mt-1 max-w-96 bg-white dark:bg-zinc-800 rounded-md shadow-lg',
        item    : 'w-full text-center px-2 py-1 text-sm text-zinc-800 dark:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-700 rounded-md transition-colors duration-200 data-[selected=true]:bg-zinc-200 dark:data-[selected=true]:bg-zinc-900',
        input   : 'block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-gray-400 focus:ring-0.5 focus:ring-gray-400 placeholder:text-gray-400 sm:text-sm disabled:bg-slate-100 disabled:text-zinc-500 dark:disabled:text-zinc-400 dark:bg-zinc-900 dark:text-zinc-300 dark:border-zinc-700 dark:disabled:bg-zinc-700',
    },
    analogic : {
        box		: 'rounded-md flex h-10 w-full select-none items-center border border-border-input dark:border-zinc-700 dark:text-zinc-300 bg-white dark:bg-zinc-900 px-2 py-3 text-sm tracking-[0.01em]-500 dark:data-[disabled]:bg-zinc-700 data-[disabled]:bg-zinc-100 focus-within:border-border-input-hover focus-within:shadow-date-field-focus hover:border-border-input-hover flex justify-between items-center px-3',
        content : 'absolute right-4 z-40 mt-1 bg-white dark:bg-zinc-900 rounded-md shadow-xl p-4',
        item    : 'transition-transform absolute w-10 h-10 flex items-center justify-center shadow-md bg-zinc-100 dark:bg-zinc-700 rounded-full text-zinc-700 dark:text-zinc-300 hover:scale-105 data-[selected=true]:bg-blue-500 dark:data-[selected=true]:bg-blue-500 data-[selected=true]:text-white data-[disabled=true]:opacity-50 data-[disabled=true]:cursor-not-allowed hover:data-[disabled=false]:bg-zinc-200 dark:hover:data-[disabled=false]:bg-zinc-600',
    },
    markdown: {
        box : 'border-b border-gray-200 dark:border-zinc-700 bg-black flex items-center h-14 dark:bg-zinc-800',
        input : 'm-2 w-full min-h-64 border-none focus:ring-0 resize-none bg-transparent dark:text-zinc-200 overflow-hidden'
    },
    none: ''
}
